const bcrypt = require('bcryptjs');

exports.seed = (knex, Promise) => {
  return knex('users').del()
    .then( () => {
      return knex('users').insert([
        {
          id: 1,
          first_name: 'Nick',
          last_name: 'Ellingson',
          email: 'nick.ellingson@email.email',
          hashed_password: `${bcrypt.hashSync('test')}`,
          profile_img_url: 'https://media.licdn.com/dms/image/C4D03AQEIVGkLqZ627A/profile-displayphoto-shrink_800_800/0?e=1539216000&v=beta&t=cVYJrsy9OeOWLFyEf0qT3e3MEyj8g3MoQmG9xs8Aj40',
          short_description: 'Sed molestias ea. Perspiciatis dicta velit quidem ut ad qui eveniet voluptatem hic. Est repellendus sunt et magni.',
          long_description: 'Unde non dolorum quae eum molestias eos reiciendis et. Quis blanditiis necessitatibus ut doloremque eius. Ex necessitatibus cum nemo veniam omnis tempore voluptatem. Velit consequatur quia ducimus eum voluptatem voluptas dolor. Et voluptas quos excepturi ut eos.',
          linkedin_url: 'www.linkedin.com/in/nickellingson',
          website_url: 'nickellingson.com',
        },
        {
          id: 2,
          first_name: 'Katie',
          last_name: 'Rice',
          email: 'katie.rice@email.email',
          hashed_password: `${bcrypt.hashSync('test')}`,
          profile_img_url: 'https://www.allianceofangels.com/wp-content/uploads/2016/04/Katie-500x500.jpg',
          short_description: 'Sed molestias ea. Perspiciatis dicta velit quidem ut ad qui eveniet voluptatem hic. Est repellendus sunt et magni.',
          long_description: 'Unde non dolorum quae eum molestias eos reiciendis et. Quis blanditiis necessitatibus ut doloremque eius. Ex necessitatibus cum nemo veniam omnis tempore voluptatem. Velit consequatur quia ducimus eum voluptatem voluptas dolor. Et voluptas quos excepturi ut eos.',
          linkedin_url: 'www.linkedin.com/in/katierice',
          website_url: 'google.com',
        },
        {
          id: 3,
          first_name: 'Audie',
          last_name: ' Koss',
          email: 'audie.koss@email.email',
          hashed_password: `${bcrypt.hashSync('test')}`,
          profile_img_url: 'https://avataaars.io/?avatarStyle=Circle&topType=LongHairNotTooLong&accessoriesType=Blank&hairColor=PastelPink&facialHairType=Blank&facialHairColor=BlondeGolden&clotheType=GraphicShirt&clotheColor=Black&graphicType=Resist&eyeType=WinkWacky&eyebrowType=SadConcernedNatural&mouthType=Default&skinColor=DarkBrown',
          short_description: 'Sed molestias ea. Perspiciatis dicta velit quidem ut ad qui eveniet voluptatem hic. Est repellendus sunt et magni.',
          long_description: 'Unde non dolorum quae eum molestias eos reiciendis et. Quis blanditiis necessitatibus ut doloremque eius. Ex necessitatibus cum nemo veniam omnis tempore voluptatem. Velit consequatur quia ducimus eum voluptatem voluptas dolor. Et voluptas quos excepturi ut eos.',
          linkedin_url: 'linkedin.com',
          website_url: 'google.com',
        },
        {
          id: 4,
          first_name: 'Faustino',
          last_name: 'King',
          email: 'faus.king@email.email',
          hashed_password: `${bcrypt.hashSync('test')}`,
          profile_img_url: 'https://avataaars.io/?avatarStyle=Circle&topType=NoHair&accessoriesType=Sunglasses&facialHairType=BeardMedium&facialHairColor=Red&clotheType=BlazerSweater&eyeType=Dizzy&eyebrowType=Default&mouthType=Default&skinColor=Brown',
          short_description: 'Sed molestias ea. Perspiciatis dicta velit quidem ut ad qui eveniet voluptatem hic. Est repellendus sunt et magni.',
          long_description: 'Unde non dolorum quae eum molestias eos reiciendis et. Quis blanditiis necessitatibus ut doloremque eius. Ex necessitatibus cum nemo veniam omnis tempore voluptatem. Velit consequatur quia ducimus eum voluptatem voluptas dolor. Et voluptas quos excepturi ut eos.',
          linkedin_url: 'linkedin.com',
          website_url: 'google.com',
        },
        {
          id: 5,
          first_name: 'Katelin',
          last_name: ' Mertz',
          email: 'ketelin.mertz@email.email',
          hashed_password: `${bcrypt.hashSync('test')}`,
          profile_img_url: 'https://avataaars.io/?avatarStyle=Circle&topType=LongHairStraightStrand&accessoriesType=Round&hairColor=Red&facialHairType=Blank&facialHairColor=Blonde&clotheType=CollarSweater&clotheColor=Blue01&eyeType=Squint&eyebrowType=RaisedExcited&mouthType=Smile&skinColor=Pale',
          short_description: 'Sed molestias ea. Perspiciatis dicta velit quidem ut ad qui eveniet voluptatem hic. Est repellendus sunt et magni.',
          long_description: 'Unde non dolorum quae eum molestias eos reiciendis et. Quis blanditiis necessitatibus ut doloremque eius. Ex necessitatibus cum nemo veniam omnis tempore voluptatem. Velit consequatur quia ducimus eum voluptatem voluptas dolor. Et voluptas quos excepturi ut eos.',
          linkedin_url: 'linkedin.com',
          website_url: 'google.com',
        },
        {
          id: 6,
          first_name: 'Telly ',
          last_name: 'Rohan',
          email: 'telly.rohan@email.email',
          hashed_password: `${bcrypt.hashSync('test')}`,
          profile_img_url: 'https://avataaars.io/?avatarStyle=Circle&topType=ShortHairDreads01&accessoriesType=Prescription02&hairColor=Auburn&facialHairType=BeardLight&facialHairColor=Black&clotheType=BlazerSweater&eyeType=Side&eyebrowType=SadConcernedNatural&mouthType=Sad&skinColor=Black',
          short_description: 'Sed molestias ea. Perspiciatis dicta velit quidem ut ad qui eveniet voluptatem hic. Est repellendus sunt et magni.',
          long_description: 'Unde non dolorum quae eum molestias eos reiciendis et. Quis blanditiis necessitatibus ut doloremque eius. Ex necessitatibus cum nemo veniam omnis tempore voluptatem. Velit consequatur quia ducimus eum voluptatem voluptas dolor. Et voluptas quos excepturi ut eos.',
          linkedin_url: 'linkedin.com',
          website_url: 'google.com',
        },
        {
          id: 7,
          first_name: 'Rocky',
          last_name: 'Schuster',
          email: 'rocky.shuster@email.email',
          hashed_password: `${bcrypt.hashSync('test')}`,
          profile_img_url: 'https://avataaars.io/?avatarStyle=Circle&topType=LongHairShavedSides&accessoriesType=Prescription01&hairColor=Brown&facialHairType=BeardLight&facialHairColor=Blonde&clotheType=Hoodie&clotheColor=Black&graphicType=Resist&eyeType=WinkWacky&eyebrowType=UpDownNatural&mouthType=Smile&skinColor=Pale',
          short_description: 'Sed molestias ea. Perspiciatis dicta velit quidem ut ad qui eveniet voluptatem hic. Est repellendus sunt et magni.',
          long_description: 'Unde non dolorum quae eum molestias eos reiciendis et. Quis blanditiis necessitatibus ut doloremque eius. Ex necessitatibus cum nemo veniam omnis tempore voluptatem. Velit consequatur quia ducimus eum voluptatem voluptas dolor. Et voluptas quos excepturi ut eos.',
          linkedin_url: 'linkedin.com',
          website_url: 'google.com',
        },
        {
          id: 8,
          first_name: 'Alford',
          last_name: 'Kirlin',
          email: 'alford.kirlin@email.email',
          hashed_password: `${bcrypt.hashSync('test')}`,
          profile_img_url: 'https://avataaars.io/?avatarStyle=Circle&topType=WinterHat3&accessoriesType=Kurt&hatColor=Red&facialHairType=BeardLight&facialHairColor=BrownDark&clotheType=GraphicShirt&clotheColor=PastelBlue&graphicType=Skull&eyeType=Surprised&eyebrowType=RaisedExcited&mouthType=Smile&skinColor=Pale',
          short_description: 'Sed molestias ea. Perspiciatis dicta velit quidem ut ad qui eveniet voluptatem hic. Est repellendus sunt et magni.',
          long_description: 'Unde non dolorum quae eum molestias eos reiciendis et. Quis blanditiis necessitatibus ut doloremque eius. Ex necessitatibus cum nemo veniam omnis tempore voluptatem. Velit consequatur quia ducimus eum voluptatem voluptas dolor. Et voluptas quos excepturi ut eos.',
          linkedin_url: 'linkedin.com',
          website_url: 'google.com',
        },
        {
          id: 9,
          first_name: 'Titus',
          last_name: 'Pfannerstill',
          email: 'titus.pfannerstill@email.email',
          hashed_password: `${bcrypt.hashSync('test')}`,
          profile_img_url: 'https://avataaars.io/?avatarStyle=Circle&topType=WinterHat4&accessoriesType=Prescription01&hatColor=Blue03&facialHairType=Blank&facialHairColor=BlondeGolden&clotheType=Overall&clotheColor=PastelBlue&eyeType=Dizzy&eyebrowType=UpDownNatural&mouthType=Disbelief&skinColor=Yellow',
          short_description: 'Sed molestias ea. Perspiciatis dicta velit quidem ut ad qui eveniet voluptatem hic. Est repellendus sunt et magni.',
          long_description: 'Unde non dolorum quae eum molestias eos reiciendis et. Quis blanditiis necessitatibus ut doloremque eius. Ex necessitatibus cum nemo veniam omnis tempore voluptatem. Velit consequatur quia ducimus eum voluptatem voluptas dolor. Et voluptas quos excepturi ut eos.',
          linkedin_url: 'linkedin.com',
          website_url: 'google.com',
        }
      ]);
    }).then(() => {
      return knex.raw(
        `SELECT setval('users_id_seq', (SELECT MAX(id) FROM users));`
      );
    });
};
