exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('tags').del()
    .then(function () {
      // Inserts seed entries
      return knex('tags').insert(
        [
          { id: 1, tag_name: '.NET' },
          { id: 2, tag_name: '3D Modeling' },
          { id: 3, tag_name: '3D Modeling / Animation' },
          { id: 4, tag_name: 'Acceptance testing' },
          { id: 5, tag_name: 'Account Management' },
          { id: 6, tag_name: 'Account Manager' },
          { id: 7, tag_name: 'Accounting' },
          { id: 8, tag_name: 'Accounts Payable' },
          { id: 9, tag_name: 'Accounts Receivable' },
          { id: 10, tag_name: 'Acquisitions' },
          { id: 11, tag_name: 'Active Directory' },
          { id: 12, tag_name: 'Administrative Assistant' },
          { id: 13, tag_name: 'Adobe' },
          { id: 14, tag_name: 'Adobe Acrobat' },
          { id: 15, tag_name: 'Adobe After Effects' },
          { id: 16, tag_name: 'Adobe Creative Suite' },
          { id: 17, tag_name: 'Adobe Illustrator' },
          { id: 18, tag_name: 'Adobe InDesign' },
          { id: 19, tag_name: 'Adobe Photoshop' },
          { id: 20, tag_name: 'Adobe Premiere' },
          { id: 21, tag_name: 'Advertising' },
          { id: 22, tag_name: 'Affiliate Marketing' },
          { id: 23, tag_name: 'Agile' },
          { id: 24, tag_name: 'Agile Project Management' },
          { id: 25, tag_name: 'Agile Software Develoment' },
          { id: 26, tag_name: 'Agile/Scrum' },
          { id: 27, tag_name: 'AJAX' },
          { id: 28, tag_name: 'Algorithms' },
          { id: 29, tag_name: 'Amazon Lambda' },
          { id: 30, tag_name: 'Amazon Redshift' },
          { id: 31, tag_name: 'Amazon S3' },
          { id: 32, tag_name: 'Amazon Web Services' },
          { id: 33, tag_name: 'Analytics' },
          { id: 34, tag_name: 'Android' },
          { id: 35, tag_name: 'Android Application Development' },
          { id: 36, tag_name: 'Android Design' },
          { id: 37, tag_name: 'Android Development' },
          { id: 38, tag_name: 'Android SDK' },
          { id: 39, tag_name: 'Android Studio' },
          { id: 40, tag_name: 'Angular' },
          { id: 41, tag_name: 'Animation' },
          { id: 42, tag_name: 'Ansible' },
          { id: 43, tag_name: 'Ansys' },
          { id: 44, tag_name: 'Ant' },
          { id: 45, tag_name: 'Apache' },
          { id: 46, tag_name: 'Apache Ant' },
          { id: 47, tag_name: 'Apache Cassandra' },
          { id: 48, tag_name: 'Apache Hadoop' },
          { id: 49, tag_name: 'Apache Kafka' },
          { id: 50, tag_name: 'Apache Maven' },
          { id: 51, tag_name: 'Apache Solr' },
          { id: 52, tag_name: 'Apache Spark' },
          { id: 53, tag_name: 'Apache Storm' },
          { id: 54, tag_name: 'Apache Tomcat' },
          { id: 55, tag_name: 'Apache Web Server' },
          { id: 56, tag_name: 'API' },
          { id: 57, tag_name: 'Apparel' },
          { id: 58, tag_name: 'Apple' },
          { id: 59, tag_name: 'Application Development' },
          { id: 60, tag_name: 'Architect' },
          { id: 61, tag_name: 'Artificial Intelligence' },
          { id: 62, tag_name: 'ASP.NET' },
          { id: 63, tag_name: 'Assembly Language' },
          { id: 64, tag_name: 'Asset Management' },
          { id: 65, tag_name: 'Atlassian JIRA' },
          { id: 66, tag_name: 'Attention to Detail' },
          { id: 67, tag_name: 'Audit' },
          { id: 68, tag_name: 'Autocad' },
          { id: 69, tag_name: 'Autodesk Autocad' },
          { id: 70, tag_name: 'Autodesk Maya' },
          { id: 71, tag_name: 'Automation' },
          { id: 72, tag_name: 'Automotive' },
          { id: 73, tag_name: 'AWS' },
          { id: 74, tag_name: 'AWS Cloud Services' },
          { id: 75, tag_name: 'AWS Lambda' },
          { id: 76, tag_name: 'Axure' },
          { id: 77, tag_name: 'B2B Marketing' },
          { id: 78, tag_name: 'B2B Sales' },
          { id: 79, tag_name: 'BabelJS' },
          { id: 80, tag_name: 'Backbone.js' },
          { id: 81, tag_name: 'Backend Development' },
          { id: 82, tag_name: 'Bash' },
          { id: 83, tag_name: 'Bash Scripting' },
          { id: 84, tag_name: 'Big Data' },
          { id: 85, tag_name: 'Big Data Analysis' },
          { id: 86, tag_name: 'Big Data Analytics' },
          { id: 87, tag_name: 'Bilingual' },
          { id: 88, tag_name: 'Billing' },
          { id: 89, tag_name: 'Bitbucket' },
          { id: 90, tag_name: 'Blogging' },
          { id: 91, tag_name: 'Bloomberg' },
          { id: 92, tag_name: 'Bluetooth' },
          { id: 93, tag_name: 'Bootstrap' },
          { id: 94, tag_name: 'Brand and Identity Design' },
          { id: 95, tag_name: 'Brand Design and Strategy' },
          { id: 96, tag_name: 'Brand Management' },
          { id: 97, tag_name: 'Budgeting' },
          { id: 98, tag_name: 'Business Analysis' },
          { id: 99, tag_name: 'Business Analyst' },
          { id: 100, tag_name: 'Business Development' },
          { id: 101, tag_name: 'Business Intelligence' },
          { id: 102, tag_name: 'Business Management' },
          { id: 103, tag_name: 'Business Operations' },
          { id: 104, tag_name: 'Business Plan' },
          { id: 105, tag_name: 'Business Planning' },
          { id: 106, tag_name: 'Business Strategy' },
          { id: 107, tag_name: 'Buying' },
          { id: 108, tag_name: 'C' },
          { id: 109, tag_name: 'C Sharp (C#)' },
          { id: 110, tag_name: 'C#' },
          { id: 111, tag_name: 'C#.NET' },
          { id: 112, tag_name: 'C++' },
          { id: 113, tag_name: 'Call Center' },
          { id: 114, tag_name: 'Capital Markets' },
          { id: 115, tag_name: 'Cassandra' },
          { id: 116, tag_name: 'Celery' },
          { id: 117, tag_name: 'Change Management' },
          { id: 118, tag_name: 'Channel Development' },
          { id: 119, tag_name: 'Chef' },
          { id: 120, tag_name: 'Chemistry' },
          { id: 121, tag_name: 'Cisco' },
          { id: 122, tag_name: 'Citrix' },
          { id: 123, tag_name: 'Client Onboarding' },
          { id: 124, tag_name: 'Client Relations' },
          { id: 125, tag_name: 'Client Relationship Management' },
          { id: 126, tag_name: 'Clojure' },
          { id: 127, tag_name: 'Closing Deals' },
          { id: 128, tag_name: 'Cloud Computing' },
          { id: 129, tag_name: 'Clustering' },
          { id: 130, tag_name: 'CMS' },
          { id: 131, tag_name: 'Coaching' },
          { id: 132, tag_name: 'Codeigniter' },
          { id: 133, tag_name: 'Coding' },
          { id: 134, tag_name: 'Coffeescript' },
          { id: 135, tag_name: 'Cold Calling' },
          { id: 136, tag_name: 'Communication Skills' },
          { id: 137, tag_name: 'Communications' },
          { id: 138, tag_name: 'Community Building' },
          { id: 139, tag_name: 'Community Development' },
          { id: 140, tag_name: 'Community Management' },
          { id: 141, tag_name: 'Community Outreach' },
          { id: 142, tag_name: 'Compensation and Benefits' },
          { id: 143, tag_name: 'Competitive Analysis' },
          { id: 144, tag_name: 'Compliance' },
          { id: 145, tag_name: 'Composer' },
          { id: 146, tag_name: 'Computer Vision' },
          { id: 147, tag_name: 'Configuration Management' },
          { id: 148, tag_name: 'Confluence' },
          { id: 149, tag_name: 'Construction' },
          { id: 150, tag_name: 'Consultative Sales' },
          { id: 151, tag_name: 'Consulting' },
          { id: 152, tag_name: 'Consumer Products' },
          { id: 153, tag_name: 'Content' },
          { id: 154, tag_name: 'Content Creation' },
          { id: 155, tag_name: 'Content Management' },
          { id: 156, tag_name: 'Content Marketing' },
          { id: 157, tag_name: 'Content Strategy' },
          { id: 158, tag_name: 'Content Writing' },
          { id: 159, tag_name: 'Continuous Deployment' },
          { id: 160, tag_name: 'Continuous Integration' },
          { id: 161, tag_name: 'Contract Negotiations' },
          { id: 162, tag_name: 'Control Systems' },
          { id: 163, tag_name: 'Conversion Optimization' },
          { id: 164, tag_name: 'Copywriting' },
          { id: 165, tag_name: 'CorelDraw' },
          { id: 166, tag_name: 'Creative Direction' },
          { id: 167, tag_name: 'Creative Problem Solving' },
          { id: 168, tag_name: 'Creative Strategy' },
          { id: 169, tag_name: 'Creative Writing' },
          { id: 170, tag_name: 'CRM' },
          { id: 171, tag_name: 'Crystal Reports' },
          { id: 172, tag_name: 'CSS' },
          { id: 173, tag_name: 'Customer Acquisition' },
          { id: 174, tag_name: 'Customer Development' },
          { id: 175, tag_name: 'Customer Experience' },
          { id: 176, tag_name: 'Customer Relationship Management' },
          { id: 177, tag_name: 'Customer Service' },
          { id: 178, tag_name: 'Customer Success' },
          { id: 179, tag_name: 'D3.js' },
          { id: 180, tag_name: 'Data Analysis' },
          { id: 181, tag_name: 'Data Entry' },
          { id: 182, tag_name: 'Data Management' },
          { id: 183, tag_name: 'Data Migration' },
          { id: 184, tag_name: 'Data Mining' },
          { id: 185, tag_name: 'Data Processing' },
          { id: 186, tag_name: 'Data Science' },
          { id: 187, tag_name: 'Data Visualization' },
          { id: 188, tag_name: 'Data Warehouse' },
          { id: 189, tag_name: 'Database and Systems Design' },
          { id: 190, tag_name: 'Database Management' },
          { id: 191, tag_name: 'Databases' },
          { id: 192, tag_name: 'DBMS' },
          { id: 193, tag_name: 'Debugging' },
          { id: 194, tag_name: 'Deep Learning' },
          { id: 195, tag_name: 'Demand Generation' },
          { id: 196, tag_name: 'Derivatives' },
          { id: 197, tag_name: 'Design' },
          { id: 198, tag_name: 'Design Management' },
          { id: 199, tag_name: 'Design Patterns' },
          { id: 200, tag_name: 'Design Research' },
          { id: 201, tag_name: 'Design Strategy' },
          { id: 202, tag_name: 'Design Thinking' },
          { id: 203, tag_name: 'DevOps' },
          { id: 204, tag_name: 'Digital Marketing' },
          { id: 205, tag_name: 'Digital Marketing Strategy' },
          { id: 206, tag_name: 'Digital Media' },
          { id: 207, tag_name: 'Digital Strategy' },
          { id: 208, tag_name: 'Disaster Recovery' },
          { id: 209, tag_name: 'Display Advertising' },
          { id: 210, tag_name: 'Distributed Systems' },
          { id: 211, tag_name: 'Distribution' },
          { id: 212, tag_name: 'Django' },
          { id: 213, tag_name: 'Docker' },
          { id: 214, tag_name: 'Documentation' },
          { id: 215, tag_name: 'DOS' },
          { id: 216, tag_name: 'Drafting' },
          { id: 217, tag_name: 'Dreamweaver' },
          { id: 218, tag_name: 'Drupal' },
          { id: 219, tag_name: 'Due Diligence' },
          { id: 220, tag_name: 'DynamoDB' },
          { id: 221, tag_name: 'E-Commerce' },
          { id: 222, tag_name: 'Eclipse' },
          { id: 223, tag_name: 'Eclipse IDE' },
          { id: 224, tag_name: 'Ecommerce' },
          { id: 225, tag_name: 'Economics' },
          { id: 226, tag_name: 'Editing' },
          { id: 227, tag_name: 'Education' },
          { id: 228, tag_name: 'ElasticSearch' },
          { id: 229, tag_name: 'ElasticSearch' },
          { id: 230, tag_name: 'Electrical Engineering' },
          { id: 231, tag_name: 'Electronics' },
          { id: 232, tag_name: 'Elixir' },
          { id: 233, tag_name: 'Email' },
          { id: 234, tag_name: 'Email Marketing' },
          { id: 235, tag_name: 'Embedded Systems' },
          { id: 236, tag_name: 'Employee Relations' },
          { id: 237, tag_name: 'Encryption' },
          { id: 238, tag_name: 'Engineering' },
          { id: 239, tag_name: 'Engineering Management' },
          { id: 240, tag_name: 'Enterprise Sales' },
          { id: 241, tag_name: 'Enterprise Software' },
          { id: 242, tag_name: 'Entertainment' },
          { id: 243, tag_name: 'Entrepreneurship' },
          { id: 244, tag_name: 'Equity' },
          { id: 245, tag_name: 'Erlang' },
          { id: 246, tag_name: 'Es6' },
          { id: 247, tag_name: 'ETL' },
          { id: 248, tag_name: 'Event Coordination' },
          { id: 249, tag_name: 'Event Management' },
          { id: 250, tag_name: 'Event Planning' },
          { id: 251, tag_name: 'Events' },
          { id: 252, tag_name: 'Excellent Communication Skills' },
          { id: 253, tag_name: 'Executive Assistant' },
          { id: 254, tag_name: 'Experience Design' },
          { id: 255, tag_name: 'Express.js' },
          { id: 256, tag_name: 'Fabrication' },
          { id: 257, tag_name: 'Facebook' },
          { id: 258, tag_name: 'Facebook Advertising' },
          { id: 259, tag_name: 'Facebook API' },
          { id: 260, tag_name: 'Fashion' },
          { id: 261, tag_name: 'Field Sales' },
          { id: 262, tag_name: 'Filing' },
          { id: 263, tag_name: 'Final Cut' },
          { id: 264, tag_name: 'Financial Analysis' },
          { id: 265, tag_name: 'Financial Management' },
          { id: 266, tag_name: 'Financial Modeling' },
          { id: 267, tag_name: 'Financial Models' },
          { id: 268, tag_name: 'Financial Reporting' },
          { id: 269, tag_name: 'Financial Services' },
          { id: 270, tag_name: 'Financial Statements' },
          { id: 271, tag_name: 'Firebase' },
          { id: 272, tag_name: 'Firewall' },
          { id: 273, tag_name: 'Firmware' },
          { id: 274, tag_name: 'Flash' },
          { id: 275, tag_name: 'Focus' },
          { id: 276, tag_name: 'Forecasting' },
          { id: 277, tag_name: 'Fraud' },
          { id: 278, tag_name: 'French language' },
          { id: 279, tag_name: 'Front-End Development' },
          { id: 280, tag_name: 'Frontend Development' },
          { id: 281, tag_name: 'Full Stack Development' },
          { id: 282, tag_name: 'Functional Testing' },
          { id: 283, tag_name: 'Funnel Optimization' },
          { id: 284, tag_name: 'Game Design' },
          { id: 285, tag_name: 'General Ledger' },
          { id: 286, tag_name: 'Git' },
          { id: 287, tag_name: 'Github' },
          { id: 288, tag_name: 'Go' },
          { id: 289, tag_name: 'Google Adwords' },
          { id: 290, tag_name: 'Google Analytics' },
          { id: 291, tag_name: 'Google Cloud Platform' },
          { id: 292, tag_name: 'Google Maps API' },
          { id: 293, tag_name: 'Government' },
          { id: 294, tag_name: 'Groovy' },
          { id: 295, tag_name: 'Growth Hacking' },
          { id: 296, tag_name: 'Grunt' },
          { id: 297, tag_name: 'Gulp' },
          { id: 298, tag_name: 'Hadoop' },
          { id: 299, tag_name: 'Hardware Engineering' },
          { id: 300, tag_name: 'Hbase' },
          { id: 301, tag_name: 'Help Desk' },
          { id: 302, tag_name: 'Heroku' },
          { id: 303, tag_name: 'Hibernate' },
          { id: 304, tag_name: 'Hiring' },
          { id: 305, tag_name: 'Hive' },
          { id: 306, tag_name: 'HP' },
          { id: 307, tag_name: 'HR' },
          { id: 308, tag_name: 'HR Management' },
          { id: 309, tag_name: 'HTML' },
          { id: 310, tag_name: 'HTML5' },
          { id: 311, tag_name: 'HTTPS' },
          { id: 312, tag_name: 'HubSpot' },
          { id: 313, tag_name: 'Human Resources' },
          { id: 314, tag_name: 'IBM' },
          { id: 315, tag_name: 'IBM DB2' },
          { id: 316, tag_name: 'IBM Websphere' },
          { id: 317, tag_name: 'Icon Design' },
          { id: 318, tag_name: 'Illustration' },
          { id: 319, tag_name: 'Image Processing' },
          { id: 320, tag_name: 'Imaging' },
          { id: 321, tag_name: 'Inbound Marketing' },
          { id: 322, tag_name: 'Industrial Design' },
          { id: 323, tag_name: 'Influencer Marketing' },
          { id: 324, tag_name: 'Informatica' },
          { id: 325, tag_name: 'Information Security' },
          { id: 326, tag_name: 'Information Technology' },
          { id: 327, tag_name: 'Infrastructure' },
          { id: 328, tag_name: 'Inside Sales' },
          { id: 329, tag_name: 'Instagram Marketing' },
          { id: 330, tag_name: 'Instrumentation' },
          { id: 331, tag_name: 'Insurance' },
          { id: 332, tag_name: 'Integration Testing' },
          { id: 333, tag_name: 'Integrity' },
          { id: 334, tag_name: 'Interaction Design' },
          { id: 335, tag_name: 'Interactive Design' },
          { id: 336, tag_name: 'Interface Design' },
          { id: 337, tag_name: 'Internal Audit' },
          { id: 338, tag_name: 'International Sales' },
          { id: 339, tag_name: 'Internet' },
          { id: 340, tag_name: 'Internet Marketing' },
          { id: 341, tag_name: 'Inventory Management' },
          { id: 342, tag_name: 'Investment Banking' },
          { id: 343, tag_name: 'Investor Relations' },
          { id: 344, tag_name: 'Invision' },
          { id: 345, tag_name: 'iOS' },
          { id: 346, tag_name: 'iOS Design' },
          { id: 347, tag_name: 'iOS Development' },
          { id: 348, tag_name: 'ISO' },
          { id: 349, tag_name: 'IT Management' },
          { id: 350, tag_name: 'ITIL' },
          { id: 351, tag_name: 'Java' },
          { id: 352, tag_name: 'Java J2EE' },
          { id: 353, tag_name: 'Java Server Pages' },
          { id: 354, tag_name: 'Javascript' },
          { id: 355, tag_name: 'Javascript Frameworks' },
          { id: 356, tag_name: 'JBoss' },
          { id: 357, tag_name: 'JDBC' },
          { id: 358, tag_name: 'Jenkins' },
          { id: 359, tag_name: 'Jira' },
          { id: 360, tag_name: 'JMeter' },
          { id: 361, tag_name: 'Journalism' },
          { id: 362, tag_name: 'jQuery' },
          { id: 363, tag_name: 'jQuery Mobile' },
          { id: 364, tag_name: 'JSON' },
          { id: 365, tag_name: 'JSON / XML' },
          { id: 366, tag_name: 'JUNIT' },
          { id: 367, tag_name: 'JVM' },
          { id: 368, tag_name: 'Kafka' },
          { id: 369, tag_name: 'Kanban' },
          { id: 370, tag_name: 'Kotlin' },
          { id: 371, tag_name: 'Kubernetes' },
          { id: 372, tag_name: 'Landing Page Optimization' },
          { id: 373, tag_name: 'Laravel' },
          { id: 374, tag_name: 'Layout' },
          { id: 375, tag_name: 'Lead Generation' },
          { id: 376, tag_name: 'Leadership' },
          { id: 377, tag_name: 'Leadership Development' },
          { id: 378, tag_name: 'LESS' },
          { id: 379, tag_name: 'Licensing' },
          { id: 380, tag_name: 'Linkedin Marketing' },
          { id: 381, tag_name: 'Linux' },
          { id: 382, tag_name: 'Linux System Administration' },
          { id: 383, tag_name: 'Litigation' },
          { id: 384, tag_name: 'Logistics' },
          { id: 385, tag_name: 'Logo Design' },
          { id: 386, tag_name: 'Lotus Notes' },
          { id: 387, tag_name: 'Mac OS X' },
          { id: 388, tag_name: 'Machine Learning' },
          { id: 389, tag_name: 'MAGENTO' },
          { id: 390, tag_name: 'Mailchimp' },
          { id: 391, tag_name: 'Management' },
          { id: 392, tag_name: 'Manual Testing' },
          { id: 393, tag_name: 'Manufacturing' },
          { id: 394, tag_name: 'Market Research' },
          { id: 395, tag_name: 'Marketing Automation' },
          { id: 396, tag_name: 'Marketing Communications' },
          { id: 397, tag_name: 'Marketing Management' },
          { id: 398, tag_name: 'Marketing Research' },
          { id: 399, tag_name: 'Marketing Strategy' },
          { id: 400, tag_name: 'Matlab' },
          { id: 401, tag_name: 'Maven' },
          { id: 402, tag_name: 'MBA' },
          { id: 403, tag_name: 'Mechanical Design' },
          { id: 404, tag_name: 'Mechanical Engineering' },
          { id: 405, tag_name: 'Media Relations' },
          { id: 406, tag_name: 'Medical' },
          { id: 407, tag_name: 'Memcached' },
          { id: 408, tag_name: 'Merchandising' },
          { id: 409, tag_name: 'Messaging' },
          { id: 410, tag_name: 'Metrics' },
          { id: 411, tag_name: 'Microsoft' },
          { id: 412, tag_name: 'Microsoft .NET' },
          { id: 413, tag_name: 'Microsoft Access' },
          { id: 414, tag_name: 'Microsoft Active Directory' },
          { id: 415, tag_name: 'Microsoft Azure' },
          { id: 416, tag_name: 'Microsoft Excel' },
          { id: 417, tag_name: 'Microsoft Exchange' },
          { id: 418, tag_name: 'Microsoft Office' },
          { id: 419, tag_name: 'Microsoft Outlook' },
          { id: 420, tag_name: 'Microsoft PowerPoint' },
          { id: 421, tag_name: 'Microsoft Project' },
          { id: 422, tag_name: 'Microsoft SQL Server' },
          { id: 423, tag_name: 'Microsoft Visio' },
          { id: 424, tag_name: 'Microsoft Visual Basic' },
          { id: 425, tag_name: 'Microsoft Visual Studio' },
          { id: 426, tag_name: 'Microsoft Windows' },
          { id: 427, tag_name: 'Microsoft Windows XP 7 8 8.1 10' },
          { id: 428, tag_name: 'Microsoft Word' },
          { id: 429, tag_name: 'Middleware' },
          { id: 430, tag_name: 'Mining' },
          { id: 431, tag_name: 'Mobile' },
          { id: 432, tag_name: 'Mobile Advertising' },
          { id: 433, tag_name: 'Mobile Application Design' },
          { id: 434, tag_name: 'Mobile Application Development' },
          { id: 435, tag_name: 'Mobile Design' },
          { id: 436, tag_name: 'Mobile Development' },
          { id: 437, tag_name: 'Mobile UI Design' },
          { id: 438, tag_name: 'Mobile UI Interaction' },
          { id: 439, tag_name: 'Mobile User Experience' },
          { id: 440, tag_name: 'Mockups' },
          { id: 441, tag_name: 'MongoDB' },
          { id: 442, tag_name: 'Monitoring' },
          { id: 443, tag_name: 'Motion Graphics' },
          { id: 444, tag_name: 'MS Office' },
          { id: 445, tag_name: 'Ms Project' },
          { id: 446, tag_name: 'MS SQL Server' },
          { id: 447, tag_name: 'Multimedia' },
          { id: 448, tag_name: 'Mvc' },
          { id: 449, tag_name: 'MySQL' },
          { id: 450, tag_name: 'Natural Language Processing' },
          { id: 451, tag_name: 'Negotiation' },
          { id: 452, tag_name: 'Negotiation Skills' },
          { id: 453, tag_name: 'Neo4J' },
          { id: 454, tag_name: 'Netbeans' },
          { id: 455, tag_name: 'Network Security' },
          { id: 456, tag_name: 'Networking' },
          { id: 457, tag_name: 'Neural Networks' },
          { id: 458, tag_name: 'New Business Development' },
          { id: 459, tag_name: 'Nginx' },
          { id: 460, tag_name: 'Node.js' },
          { id: 461, tag_name: 'NodeJS' },
          { id: 462, tag_name: 'noSQL' },
          { id: 463, tag_name: 'Numpy' },
          { id: 464, tag_name: 'Object Oriented Programming' },
          { id: 465, tag_name: 'Objective-C' },
          { id: 466, tag_name: 'Office Administration' },
          { id: 467, tag_name: 'Office Management' },
          { id: 468, tag_name: 'Online Marketing' },
          { id: 469, tag_name: 'OpenCV' },
          { id: 470, tag_name: 'OpenGL' },
          { id: 471, tag_name: 'Operating Systems' },
          { id: 472, tag_name: 'Operations Management' },
          { id: 473, tag_name: 'Oracle' },
          { id: 474, tag_name: 'Oracle 10g' },
          { id: 475, tag_name: 'Oracle 11g' },
          { id: 476, tag_name: 'Organization' },
          { id: 477, tag_name: 'Origami' },
          { id: 478, tag_name: 'Outside Sales' },
          { id: 479, tag_name: 'Outsourcing' },
          { id: 480, tag_name: 'P&amp;L' },
          { id: 481, tag_name: 'Packaging' },
          { id: 482, tag_name: 'Paid Search Advertising' },
          { id: 483, tag_name: 'Payroll' },
          { id: 484, tag_name: 'PC' },
          { id: 485, tag_name: 'People Management' },
          { id: 486, tag_name: 'PeopleSoft' },
          { id: 487, tag_name: 'Performance Testing' },
          { id: 488, tag_name: 'Performance Tuning' },
          { id: 489, tag_name: 'Perl' },
          { id: 490, tag_name: 'Pharmaceutical' },
          { id: 491, tag_name: 'Phone Skills' },
          { id: 492, tag_name: 'PhoneGap/Cordova' },
          { id: 493, tag_name: 'Photography' },
          { id: 494, tag_name: 'PHP' },
          { id: 495, tag_name: 'Pig' },
          { id: 496, tag_name: 'Planning' },
          { id: 497, tag_name: 'PMP' },
          { id: 498, tag_name: 'Portfolio Management' },
          { id: 499, tag_name: 'POS' },
          { id: 500, tag_name: 'PostgreSQL' },
          { id: 501, tag_name: 'PPC' },
          { id: 502, tag_name: 'PR' },
          { id: 503, tag_name: 'Predictive Analytics' },
          { id: 504, tag_name: 'Presentation Skills' },
          { id: 505, tag_name: 'Press Release Writing' },
          { id: 506, tag_name: 'Pricing' },
          { id: 507, tag_name: 'Print Design' },
          { id: 508, tag_name: 'Private Equity' },
          { id: 509, tag_name: 'Problem Solving' },
          { id: 510, tag_name: 'Problem Solving Skills' },
          { id: 511, tag_name: 'Process Improvement' },
          { id: 512, tag_name: 'Process improvements' },
          { id: 513, tag_name: 'Process Management' },
          { id: 514, tag_name: 'Procurement' },
          { id: 515, tag_name: 'Product' },
          { id: 516, tag_name: 'Product Design' },
          { id: 517, tag_name: 'Product Development' },
          { id: 518, tag_name: 'Product Evangelism' },
          { id: 519, tag_name: 'Product Launch' },
          { id: 520, tag_name: 'Product Management' },
          { id: 521, tag_name: 'Product Marketing' },
          { id: 522, tag_name: 'Product Strategy' },
          { id: 523, tag_name: 'Professional Services' },
          { id: 524, tag_name: 'Program Management' },
          { id: 525, tag_name: 'Program Manager' },
          { id: 526, tag_name: 'Programming' },
          { id: 527, tag_name: 'Programming Languages' },
          { id: 528, tag_name: 'Programming: 3P APIs &amp; Libraries' },
          { id: 529, tag_name: 'Project Coordinator' },
          { id: 530, tag_name: 'Project Leader' },
          { id: 531, tag_name: 'Project Manager' },
          { id: 532, tag_name: 'Proofreading' },
          { id: 533, tag_name: 'Prospecting' },
          { id: 534, tag_name: 'Prototyping' },
          { id: 535, tag_name: 'Public Relations' },
          { id: 536, tag_name: 'Public Speaking' },
          { id: 537, tag_name: 'Publications' },
          { id: 538, tag_name: 'Publishing' },
          { id: 539, tag_name: 'Puppet' },
          { id: 540, tag_name: 'Purchasing' },
          { id: 541, tag_name: 'Python' },
          { id: 542, tag_name: 'QA' },
          { id: 543, tag_name: 'Quality' },
          { id: 544, tag_name: 'Quality Assurance' },
          { id: 545, tag_name: 'Quality Control' },
          { id: 546, tag_name: 'Quality Management' },
          { id: 547, tag_name: 'Quick Books' },
          { id: 548, tag_name: 'Quickbooks' },
          { id: 549, tag_name: 'R' },
          { id: 550, tag_name: 'Rabbitmq' },
          { id: 551, tag_name: 'Rapid Prototyping' },
          { id: 552, tag_name: 'RDBMS' },
          { id: 553, tag_name: 'React Native' },
          { id: 554, tag_name: 'React.js' },
          { id: 555, tag_name: 'Real Estate' },
          { id: 556, tag_name: 'Reconciliations' },
          { id: 557, tag_name: 'Recruiter' },
          { id: 558, tag_name: 'Recruiting' },
          { id: 559, tag_name: 'Recruiting/Onboarding/Training New Hires' },
          { id: 560, tag_name: 'Recruiting/Talent Acquisition/ HR Reporting' },
          { id: 561, tag_name: 'Recruitment' },
          { id: 562, tag_name: 'Redhat' },
          { id: 563, tag_name: 'Redis' },
          { id: 564, tag_name: 'Redux' },
          { id: 565, tag_name: 'Regression Testing' },
          { id: 566, tag_name: 'Relational Databases' },
          { id: 567, tag_name: 'Relationship Building' },
          { id: 568, tag_name: 'Reliability' },
          { id: 569, tag_name: 'Requirements Analysis' },
          { id: 570, tag_name: 'Requirements Gathering' },
          { id: 571, tag_name: 'Research' },
          { id: 572, tag_name: 'Research and Development' },
          { id: 573, tag_name: 'Responsive Design' },
          { id: 574, tag_name: 'REST' },
          { id: 575, tag_name: 'REST APIs' },
          { id: 576, tag_name: 'Retail' },
          { id: 577, tag_name: 'Retail Sales' },
          { id: 578, tag_name: 'Retention' },
          { id: 579, tag_name: 'Revenue Growth' },
          { id: 580, tag_name: 'Risk Analysis' },
          { id: 581, tag_name: 'Risk Assessment' },
          { id: 582, tag_name: 'Risk Management' },
          { id: 583, tag_name: 'Robotics' },
          { id: 584, tag_name: 'Root Cause Analysis' },
          { id: 585, tag_name: 'Routers' },
          { id: 586, tag_name: 'Rspec' },
          { id: 587, tag_name: 'Ruby' },
          { id: 588, tag_name: 'Ruby on Rails' },
          { id: 589, tag_name: 'SaaS' },
          { id: 590, tag_name: 'SaaS Sales' },
          { id: 591, tag_name: 'Sales' },
          { id: 592, tag_name: 'Sales and Marketing' },
          { id: 593, tag_name: 'Sales Development' },
          { id: 594, tag_name: 'Sales Engineering' },
          { id: 595, tag_name: 'Sales Management' },
          { id: 596, tag_name: 'Sales Operations' },
          { id: 597, tag_name: 'Sales Strategy and Management' },
          { id: 598, tag_name: 'Sales Support' },
          { id: 599, tag_name: 'Sales Training' },
          { id: 600, tag_name: 'Salesforce' },
          { id: 601, tag_name: 'Salesforce Developer' },
          { id: 602, tag_name: 'SalesForce.com' },
          { id: 603, tag_name: 'SAP' },
          { id: 604, tag_name: 'SAS' },
          { id: 605, tag_name: 'Scala' },
          { id: 606, tag_name: 'Scheduling' },
          { id: 607, tag_name: 'Science' },
          { id: 608, tag_name: 'Scripting Languages' },
          { id: 609, tag_name: 'SCRUM' },
          { id: 610, tag_name: 'Scrum Master' },
          { id: 611, tag_name: 'SCSS / SASS' },
          { id: 612, tag_name: 'SDK' },
          { id: 613, tag_name: 'SDLC' },
          { id: 614, tag_name: 'Search Engine Marketing (SEM)' },
          { id: 615, tag_name: 'Search Engine Optimization' },
          { id: 616, tag_name: 'Securities' },
          { id: 617, tag_name: 'Security' },
          { id: 618, tag_name: 'Selenium' },
          { id: 619, tag_name: 'Selenium WebDriver' },
          { id: 620, tag_name: 'SEO' },
          { id: 621, tag_name: 'SEO/SEM' },
          { id: 622, tag_name: 'Servers' },
          { id: 623, tag_name: 'Services' },
          { id: 624, tag_name: 'Servlets' },
          { id: 625, tag_name: 'SharePoint' },
          { id: 626, tag_name: 'Shell Scripting' },
          { id: 627, tag_name: 'Shopify' },
          { id: 628, tag_name: 'Sketch' },
          { id: 629, tag_name: 'Sketching' },
          { id: 630, tag_name: 'Social Media' },
          { id: 631, tag_name: 'Social Media Management' },
          { id: 632, tag_name: 'Social Media Marketing' },
          { id: 633, tag_name: 'Social Media Strategy' },
          { id: 634, tag_name: 'Social Networking' },
          { id: 635, tag_name: 'Socket.io' },
          { id: 636, tag_name: 'Software' },
          { id: 637, tag_name: 'Software Architecture' },
          { id: 638, tag_name: 'Software Design' },
          { id: 639, tag_name: 'Software Development' },
          { id: 640, tag_name: 'Software Sales' },
          { id: 641, tag_name: 'Software Testing' },
          { id: 642, tag_name: 'Solidworks' },
          { id: 643, tag_name: 'Solutions Selling' },
          { id: 644, tag_name: 'Sourcing' },
          { id: 645, tag_name: 'Spark' },
          { id: 646, tag_name: 'Sports' },
          { id: 647, tag_name: 'Spring' },
          { id: 648, tag_name: 'SPSS' },
          { id: 649, tag_name: 'SQL' },
          { id: 650, tag_name: 'SQL Server' },
          { id: 651, tag_name: 'SQL/MySQL/PostgreSQL' },
          { id: 652, tag_name: 'SQLite' },
          { id: 653, tag_name: 'Statistical Analysis' },
          { id: 654, tag_name: 'Statistics' },
          { id: 655, tag_name: 'Storage Area Networks' },
          { id: 656, tag_name: 'Stored procedures' },
          { id: 657, tag_name: 'Strategic Partnerships' },
          { id: 658, tag_name: 'Strategic Planning' },
          { id: 659, tag_name: 'Strong Work Ethic' },
          { id: 660, tag_name: 'Struts' },
          { id: 661, tag_name: 'Subversion' },
          { id: 662, tag_name: 'Supply Chain Management' },
          { id: 663, tag_name: 'Support' },
          { id: 664, tag_name: 'Svn' },
          { id: 665, tag_name: 'Swift' },
          { id: 666, tag_name: 'Symfony' },
          { id: 667, tag_name: 'System Administration' },
          { id: 668, tag_name: 'System Design' },
          { id: 669, tag_name: 'System Integration' },
          { id: 670, tag_name: 'System testing' },
          { id: 671, tag_name: 'Systems Administration' },
          { id: 672, tag_name: 'Tableau' },
          { id: 673, tag_name: 'Tableau Software' },
          { id: 674, tag_name: 'Talent Acquisition' },
          { id: 675, tag_name: 'Talent Management' },
          { id: 676, tag_name: 'TCP/IP' },
          { id: 677, tag_name: 'TDD' },
          { id: 678, tag_name: 'Team Building' },
          { id: 679, tag_name: 'Team Lead' },
          { id: 680, tag_name: 'Team Player' },
          { id: 681, tag_name: 'Teamwork' },
          { id: 682, tag_name: 'Technical &amp; Customer Support' },
          { id: 683, tag_name: 'Technical documentation' },
          { id: 684, tag_name: 'Technical Leadership' },
          { id: 685, tag_name: 'Technical Recruiting' },
          { id: 686, tag_name: 'Technical Sales' },
          { id: 687, tag_name: 'Technical Support' },
          { id: 688, tag_name: 'Technical Writing' },
          { id: 689, tag_name: 'Technology' },
          { id: 690, tag_name: 'Telecommunications' },
          { id: 691, tag_name: 'Telemarketing' },
          { id: 692, tag_name: 'TensorFlow' },
          { id: 693, tag_name: 'Terraform' },
          { id: 694, tag_name: 'Test' },
          { id: 695, tag_name: 'Test Automation' },
          { id: 696, tag_name: 'Test Cases' },
          { id: 697, tag_name: 'Test Plans' },
          { id: 698, tag_name: 'Test Scripts' },
          { id: 699, tag_name: 'TFS' },
          { id: 700, tag_name: 'Time Management' },
          { id: 701, tag_name: 'Toad' },
          { id: 702, tag_name: 'Tourism' },
          { id: 703, tag_name: 'Training' },
          { id: 704, tag_name: 'Training &amp; Development' },
          { id: 705, tag_name: 'Transportation' },
          { id: 706, tag_name: 'Travel' },
          { id: 707, tag_name: 'Trello' },
          { id: 708, tag_name: 'Troubleshooting' },
          { id: 709, tag_name: 'Twitter' },
          { id: 710, tag_name: 'Twitter Bootstrap' },
          { id: 711, tag_name: 'Twitter Marketing' },
          { id: 712, tag_name: 'TypeScript' },
          { id: 713, tag_name: 'Typing' },
          { id: 714, tag_name: 'Typography' },
          { id: 715, tag_name: 'Ubuntu' },
          { id: 716, tag_name: 'UI Design' },
          { id: 717, tag_name: 'Underwriting' },
          { id: 718, tag_name: 'Unit Testing' },
          { id: 719, tag_name: 'Unity' },
          { id: 720, tag_name: 'Unity3D' },
          { id: 721, tag_name: 'Unix' },
          { id: 722, tag_name: 'Unix Shell Scripting' },
          { id: 723, tag_name: 'Unreal Engine 4' },
          { id: 724, tag_name: 'Usability Testing' },
          { id: 725, tag_name: 'Use Cases' },
          { id: 726, tag_name: 'User Acceptance Testing' },
          { id: 727, tag_name: 'User Acquisition' },
          { id: 728, tag_name: 'User Experience Design' },
          { id: 729, tag_name: 'User Experience Strategy' },
          { id: 730, tag_name: 'User Interaction Design' },
          { id: 731, tag_name: 'User Interface' },
          { id: 732, tag_name: 'User Interface Design' },
          { id: 733, tag_name: 'User Research' },
          { id: 734, tag_name: 'User-Centered Design' },
          { id: 735, tag_name: 'Utilities' },
          { id: 736, tag_name: 'UX Design' },
          { id: 737, tag_name: 'UX Research' },
          { id: 738, tag_name: 'Vagrant' },
          { id: 739, tag_name: 'Vendor Management' },
          { id: 740, tag_name: 'Venture Capital' },
          { id: 741, tag_name: 'Verbal Communication' },
          { id: 742, tag_name: 'Verilog' },
          { id: 743, tag_name: 'Version Control' },
          { id: 744, tag_name: 'VHDL' },
          { id: 745, tag_name: 'Video' },
          { id: 746, tag_name: 'Video Advertising' },
          { id: 747, tag_name: 'Video Editing' },
          { id: 748, tag_name: 'Video Production' },
          { id: 749, tag_name: 'Viral Marketing' },
          { id: 750, tag_name: 'Virtualization' },
          { id: 751, tag_name: 'Visio' },
          { id: 752, tag_name: 'Visual Basic' },
          { id: 753, tag_name: 'Visual Design' },
          { id: 754, tag_name: 'VMware' },
          { id: 755, tag_name: 'VOICE' },
          { id: 756, tag_name: 'Vue.Js' },
          { id: 757, tag_name: 'Wealth Management' },
          { id: 758, tag_name: 'WEB' },
          { id: 759, tag_name: 'Web Analytics' },
          { id: 760, tag_name: 'Web Application Design' },
          { id: 761, tag_name: 'Web Application Frameworks' },
          { id: 762, tag_name: 'Web Applications' },
          { id: 763, tag_name: 'Web Content Writer' },
          { id: 764, tag_name: 'Web Design' },
          { id: 765, tag_name: 'Web Development' },
          { id: 766, tag_name: 'Web Services' },
          { id: 767, tag_name: 'Web Technologies' },
          { id: 768, tag_name: 'WebGL' },
          { id: 769, tag_name: 'Webpack' },
          { id: 770, tag_name: 'WebRTC' },
          { id: 771, tag_name: 'Website Development/Design' },
          { id: 772, tag_name: 'Websockets' },
          { id: 773, tag_name: 'Wholesale' },
          { id: 774, tag_name: 'Windows 7' },
          { id: 775, tag_name: 'Windows Azure' },
          { id: 776, tag_name: 'Windows XP' },
          { id: 777, tag_name: 'Wireframing' },
          { id: 778, tag_name: 'Wireless' },
          { id: 779, tag_name: 'Wireshark' },
          { id: 780, tag_name: 'Wordpress' },
          { id: 781, tag_name: 'Written communication' },
          { id: 782, tag_name: 'Xamarin' },
          { id: 783, tag_name: 'Xcode' },
          { id: 784, tag_name: 'XML' },
          { id: 785, tag_name: 'ZenDesk' },
          { id: 786, tag_name: 'Zepto' }
        ]
      );
    }).then(() => {
      return knex.raw(
        `SELECT setval('tags_id_seq', (SELECT MAX(id) FROM tags));`
      );
    });
};
